AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - test/fixtures/**/*
    - test/functions.rb

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/ClassLength:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false
