AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - test/fixtures/**/*
    - test/functions.rb

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/ClassLength:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable
  AutoCorrect: true
