require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - test/fixtures/**/*
    - test/functions.rb

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
