inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - test/fixtures/**/*
    - test/functions.rb

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/FactoryBot/CreateList:
  Enabled: false

# Below can be removed if/when licensee no longer supports ruby < 3.0

Lint/RedundantDirGlobSort:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false
