language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
script: "script/cibuild"
sudo: false
cache: bundler
before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
